"""empty message

Revision ID: f7dea085cd48
Revises: 
Create Date: 2024-06-19 12:37:20.050005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7dea085cd48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('job', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('todos',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('general',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('reference_period', sa.Integer(), nullable=True),
    sa.Column('analysis_method', sa.String(length=80), nullable=True),
    sa.Column('analysis_principle', sa.String(length=80), nullable=True),
    sa.Column('main_sector', sa.String(length=80), nullable=True),
    sa.Column('no_alternatives', sa.Integer(), nullable=True),
    sa.Column('da_analysis', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('ratios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enis', sa.Float(), nullable=True),
    sa.Column('egdv', sa.Integer(), nullable=True),
    sa.Column('evgn', sa.Float(), nullable=True),
    sa.Column('sva', sa.Float(), nullable=True),
    sa.Column('da', sa.Float(), nullable=True),
    sa.Column('fgdv', sa.Integer(), nullable=True),
    sa.Column('fvgn', sa.Float(), nullable=True),
    sa.Column('fnis', sa.Float(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratios')
    op.drop_table('general')
    op.drop_table('todos')
    op.drop_table('project')
    op.drop_table('person')
    # ### end Alembic commands ###
